using InstallBunker.Compiler.Core.Models;
using InstallBunker.Compiler.Core.Services;

namespace InstallBunker.Builder.UI.Services.Compiler;

public sealed class BuilderCompilationService
{
    private readonly CompilerEngine _compilerEngine = new();

    public async Task<BuilderCompilationResult> CompileAsync(
        CompilerRequest request,
        string builderBaseDirectory,
        IProgress<CompilerTelemetryEvent>? progress = null,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(builderBaseDirectory))
        {
            throw new InvalidOperationException("Builder base directory is required.");
        }

        var result = new BuilderCompilationResult
        {
            UsedCompilerTemplates = true
        };

        result.StatusMessages.Add("Preparing package build...");
        result.StatusMessages.Add("Compiler will generate Setup.exe and Uninstall.exe through the internal publish pipeline.");

        progress?.Report(CompilerTelemetryEvent.Status(
            "builder-start",
            "Preparing Build",
            "Preparing package build...",
            1));

        result.LogMessages.Add("Delegating package generation to CompilerEngine...");
        result.LogMessages.Add("CompilerEngine will generate single-file bootstrappers through dotnet publish.");

        progress?.Report(CompilerTelemetryEvent.Log(
            "builder-start",
            "Preparing Build",
            "Delegating package generation to CompilerEngine..."));

        var compilerResult = await _compilerEngine.CompileAsync(
            request,
            builderBaseDirectory,
            progress,
            cancellationToken);

        result.CompilerResult = compilerResult;

        foreach (var log in compilerResult.Logs)
        {
            result.LogMessages.Add(log);
        }

        result.StatusMessages.Add("Package generated successfully.");
        result.StatusMessages.Add($"Output folder: {compilerResult.OutputDirectory}");
        result.StatusMessages.Add($"Toolchain source: {compilerResult.ToolchainDisplayName} ({compilerResult.ToolchainSourceKind})");

        result.LogMessages.Add("Setup.exe generated by toolchain.");
        result.LogMessages.Add("Uninstall.exe generated by toolchain.");
        result.LogMessages.Add("manifest.json generated.");
        result.LogMessages.Add($"Payload files copied: {compilerResult.FilesCopiedCount}");
        result.LogMessages.Add($"Output folder: {compilerResult.OutputDirectory}");

        if (!string.IsNullOrWhiteSpace(compilerResult.BuildLogFilePath))
        {
            result.LogMessages.Add($"Build log file: {compilerResult.BuildLogFilePath}");
        }

        if (compilerResult.UsedSystemDotNetFallback)
        {
            result.LogMessages.Add("Warning: system dotnet fallback was used.");
        }

        return result;
    }
}